[tox]
envlist = py27
minversion = 3.4.0
skip_missing_interpreters = true

[testenv]
description = Run the unit tests under {basepython}
skip_install = True
usedevelop = True
deps = tox
whitelist_externals = cargo
setenv =
    PYTHON_SYS_EXECUTABLE = c:\\python27\\python.exe
commands = cargo test src/lib.rs --features python2
           tox -c examples/word-count/tox.ini
           tox -c examples/rustapi_module/tox.ini
